---
# tasks file for ucs-lan
- name: UCS LAN Configuration

  vars:
    login_info: &login_info
      hostname: "{{ ucs_hostname }}"
      username: "{{ ucs_username }}"
      password: "{{ ucs_password }}"
      state: "{{ ucs_state }}"

  block:
  - name: Configure Block of IPv4 Addresses for KVM Access
    ucs_ip_pool:
      <<: *login_info
      name: "{{ item.name }}"
      first_addr: "{{ item.first_addr }}"
      last_addr: "{{ item.last_addr }}"
      subnet_mask: "{{ item.subnet_mask }}"
      default_gw: "{{ item.default_gw }}"
    with_items: "{{ ucs_lan_data.ip_pools }}"
    
  - name: Configure MAC Address Pools
    ucs_mac_pool:
      <<: *login_info
      name: "{{ item.name }}"
      first_addr: "{{ item.first_addr }}"
      last_addr: "{{ item.last_addr }}"
      order: "{{ item.order }}"
    with_items: "{{ ucs_lan_data.mac_pools }}"

  - name: Configure VLANs
    ucs_vlans:
      <<: *login_info
      name: "{{ item.name }}"
      id: "{{ item.id }}"
      native: "{{ item.native | default(omit) }}"
    with_items: "{{ ucs_lan_data.vlans }}"

  - name: Configure vNIC Templates
    ucs_vnic_template:
      <<: *login_info
      name: "{{ item.name }}"
      fabric: "{{ item.fabric }}"
      redundancy_type: "{{ item.redundancy_type | default(omit) }}"
      peer_redundancy_templ: "{{ item.peer_redundancy_templ | default(omit) }}"
      template_type: "{{ item.template_type | default(omit) }}"
      mtu: "{{ item.mtu | default(omit) }}"
      mac_pool: "{{ item.mac_pool }}"
      network_control_policy: "{{ item.network_control_policy | default(omit) }}"
      vlans_list: "{{ item.vlans_list | default(omit) }}"
    with_items: "{{ ucs_lan_data.vnic_templates }}"

  - name: Configure LAN Connectivity Policies
    ucs_lan_connectivity:
      <<: *login_info
      name: "{{ item.name }}"
      vnic_list: "{{ item.vnic_list }}"
    with_items: "{{ ucs_lan_data.lan_connectivity_policies }}"
